import os
from github import Github


def main():
    # === 1. Получаем переменные окружения ===
    token = os.getenv("GITHUB_TOKEN")
    repo_name = os.getenv("GITHUB_REPOSITORY")
    issue_number = os.getenv("ISSUE_NUMBER")

    if not token or not repo_name or not issue_number:
        raise ValueError("Missing required environment variables")

    issue_number = int(issue_number)

    print(f"Repository: {repo_name}")
    print(f"Issue number: {issue_number}")

    # === 2. Подключаемся к GitHub ===
    g = Github(token)
    repo = g.get_repo(repo_name)

    issue = repo.get_issue(issue_number)
    issue_body = issue.body or ""

    print("Issue content:")
    print(issue_body)

    # === 3. Создаём ветку ===
    base_branch = "main"
    new_branch_name = f"issue-{issue_number}"

    source = repo.get_branch(base_branch)

    try:
        repo.create_git_ref(
            ref=f"refs/heads/{new_branch_name}",
            sha=source.commit.sha,
        )
        print(f"Created branch {new_branch_name}")
    except Exception:
        print("Branch already exists")

    # === 4. Модифицируем файл ===
    # Для MVP будем менять README.md
    try:
        file = repo.get_contents("README.md", ref=new_branch_name)
    except Exception:
        print("README.md not found, skipping file update")
        return

    old_content = file.decoded_content.decode()

    new_content = (
        old_content
        + "\n\n---\n"
        + f"Auto update from AI Agent for issue #{issue_number}\n"
        + f"Issue description:\n{issue_body}\n"
    )

    repo.update_file(
        path=file.path,
        message=f"Auto update for issue #{issue_number}",
        content=new_content,
        sha=file.sha,
        branch=new_branch_name,
    )

    print("File updated")

    # === 5. Создаём Pull Request ===
    try:
        repo.create_pull(
            title=f"Auto-fix for issue #{issue_number}",
            body="This PR was automatically generated by Code Agent.",
            head=new_branch_name,
            base=base_branch,
        )
        print("Pull Request created")
    except Exception as e:
        print("PR already exists or error:", e)


if __name__ == "__main__":
    main()
