import os
import subprocess
from typing import Optional

from github import Auth, Github

from agent.agno_agent import run_coding_agent


def sh(cmd: str) -> str:
    print(f"$ {cmd}")
    out = subprocess.check_output(cmd, shell=True, text=True, stderr=subprocess.STDOUT)
    print(out)
    return out


def try_sh(cmd: str) -> str:
    try:
        return sh(cmd)
    except subprocess.CalledProcessError as e:
        print(e.output)
        raise


def main() -> None:
    token = os.getenv("GITHUB_TOKEN")
    repo_name = os.getenv("GITHUB_REPOSITORY")
    issue_number_str = os.getenv("ISSUE_NUMBER")
    base_branch = (os.getenv("BASE_BRANCH") or "main").strip()

    if not token or not repo_name or not issue_number_str:
        raise ValueError("Missing env vars: GITHUB_TOKEN, GITHUB_REPOSITORY, ISSUE_NUMBER")

    issue_number = int(issue_number_str)

    auth = Auth.Token(token)
    gh = Github(auth=auth)
    repo = gh.get_repo(repo_name)

    issue = repo.get_issue(number=issue_number)
    issue_title = issue.title or ""
    issue_body = issue.body or ""

    branch = f"issue-{issue_number}"

    # 1) Create branch from base
    base = repo.get_branch(base_branch)
    try:
        repo.create_git_ref(ref=f"refs/heads/{branch}", sha=base.commit.sha)
        print(f"Created branch: {branch}")
    except Exception:
        print("Branch already exists (ok)")

    # 2) Prepare git in runner
    sh("git config user.email 'actions@github.com'")
    sh("git config user.name 'github-actions[bot]'")

    # Fetch + checkout branch locally
    sh(f"git fetch origin {branch}:{branch} || true")
    sh(f"git checkout {branch}")

    # Set authenticated remote for push
    sh(f"git remote set-url origin https://x-access-token:{token}@github.com/{repo_name}.git")

    # Clean python caches to avoid garbage commits
    sh("find . -type d -name __pycache__ -prune -exec rm -rf {} + || true")
    sh("find . -type f -name '*.pyc' -delete || true")

    # 3) Build task prompt for agent
    task = f"""
У тебя есть задача из GitHub Issue. Нужно внести изменения в этом репозитории.

Issue #{issue_number}
Title: {issue_title}

Body:
{issue_body}

Требования к работе:
1) Сначала изучи структуру проекта (list files) и найди релевантные файлы.
2) Перед изменением прочитай файлы.
3) Меняй минимально необходимое количество файлов.
4) НЕ трогай: node_modules, dist, build, .git
5) После правок попробуй прогнать команды (если применимо для фронтенда):
   - npm ci
   - npm run lint (если есть)
   - npm test (если есть)
   - npm run build (если есть)
6) Если команды упали — постарайся исправить и прогнать снова.
7) В конце напиши краткий отчёт: какие файлы изменены и почему.

Важно: файл(ы) нужно реально изменить в рабочем дереве репозитория.
"""

    # 4) Run LLM agent. If it fails -> abort without commit/PR
    try:
        report = run_coding_agent(task)
    except Exception as e:
        raise RuntimeError(f"LLM failed, aborting without PR/commit: {e}") from e

    print("=== AGENT REPORT ===")
    print(report)

    # Clean caches again (agent may have imported modules)
    sh("find . -type d -name __pycache__ -prune -exec rm -rf {} + || true")
    sh("find . -type f -name '*.pyc' -delete || true")

    # 5) Check changes
    status = subprocess.check_output("git status --porcelain", shell=True, text=True).strip()
    print("$ git status --porcelain")
    print(status)

    if not status:
        print("No changes detected. Not creating PR.")
        return

    # 6) Commit + push
    sh("git add -A")
    sh(f"git commit -m 'Auto-fix issue #{issue_number}'")
    sh(f"git push -u origin {branch}")

    # 7) Create PR if not exists
    pr_title = f"Auto-fix for issue #{issue_number}: {issue_title}".strip()
    pr_body = "This PR was automatically generated by Code Agent.\n\n---\n\n" + report

    try:
        repo.create_pull(
            title=pr_title,
            body=pr_body[:65000],  # safety limit for GitHub
            head=branch,
            base=base_branch,
        )
        print("Pull Request created")
    except Exception as e:
        # If PR already exists, this will fail; that's OK
        print(f"PR already exists or could not be created: {e}")


if __name__ == "__main__":
    main()
