# agent/code_agent.py
import os
import subprocess
from github import Github, Auth

from agent.agno_agent import run_coding_agent


def sh(cmd: str) -> str:
    print(f"$ {cmd}")
    out = subprocess.check_output(cmd, shell=True, text=True, stderr=subprocess.STDOUT)
    print(out)
    return out


def main():
    token = os.getenv("GITHUB_TOKEN")
    repo_name = os.getenv("GITHUB_REPOSITORY")
    issue_number = int(os.getenv("ISSUE_NUMBER", "0"))

    if not token or not repo_name or not issue_number:
        raise ValueError("Missing env vars: GITHUB_TOKEN, GITHUB_REPOSITORY, ISSUE_NUMBER")

    auth = Auth.Token(token)
    gh = Github(auth=auth)
    repo = gh.get_repo(repo_name)

    issue = repo.get_issue(number=issue_number)
    issue_title = issue.title or ""
    issue_body = issue.body or ""

    base_branch = "main"
    branch = f"issue-{issue_number}"

    # 1) Создаём ветку через API (как раньше)
    base = repo.get_branch(base_branch)
    try:
        repo.create_git_ref(ref=f"refs/heads/{branch}", sha=base.commit.sha)
        print(f"Created branch: {branch}")
    except Exception:
        print("Branch already exists (ok)")

    # 2) Переключаемся локально на эту ветку и настраиваем push
    sh("git config user.email 'actions@github.com'")
    sh("git config user.name 'github-actions[bot]'")
    sh(f"git fetch origin {branch}:{branch} || true")
    sh(f"git checkout {branch}")

    # важный момент: настроим remote с токеном, чтобы push работал
    sh(f"git remote set-url origin https://x-access-token:{token}@github.com/{repo_name}.git")

    # 3) Собираем задание для LLM (контекст + требования)
    task = f"""
У тебя есть задача из GitHub Issue.

Title: {issue_title}

Body:
{issue_body}

Репозиторий уже выкачан локально. Выполни:
1) Изучи структуру проекта (list files).
2) Внеси изменения, которые решают задачу.
3) Если есть линтер/тесты/сборка, запусти команды:
   - npm ci
   - npm run lint (если есть)
   - npm test (если есть)
   - npm run build (если есть)
4) Исправь проблемы, если команды упали.
5) Не меняй node_modules/dist/build/.git.
В конце напиши короткий отчёт что изменил.
"""

    # 4) Запускаем Agno-агента: он будет сам читать/писать файлы и гонять команды через tools
    report = run_coding_agent(task)
    print("=== AGENT REPORT ===")
    print(report)
    
    # Если в отчёте явная ошибка — останавливаемся
    bad_markers = ["Provider returned error", "rate-limited", "No models provided"]
    if any(x.lower() in report.lower() for x in bad_markers):
        raise RuntimeError(f"LLM failed: {report}")

    print("=== AGENT REPORT ===")
    print(report)

    # 5) Коммитим изменения (если есть)
    sh("git status --porcelain")
    changed = subprocess.check_output("git status --porcelain", shell=True, text=True).strip()
    if not changed:
        print("No changes detected; stopping.")
        return

    sh("git add -A")
    sh(f"git commit -m 'Auto-fix issue #{issue_number}'")

    # 6) Пушим ветку
    sh(f"git push -u origin {branch}")

    # 7) Создаём PR (если ещё нет)
    try:
        repo.create_pull(
            title=f"Auto-fix for issue #{issue_number}: {issue_title}",
            body="This PR was automatically generated by Code Agent.",
            head=branch,
            base=base_branch,
        )
        print("Pull Request created")
    except Exception as e:
        print("PR already exists or error:", e)


if __name__ == "__main__":
    main()
